name: build and deploy 

on:
  push:
    branches: ["main"]
  
jobs:
  build: 
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.HARBOR_PASS }} | docker login 108.143.193.224 -u ${{ secrets.HARBOR_PASS }} --password-stdin
