name: build and deploy 

on:
  push:
    branches: ["main"]
  
jobs:
  build: 
    name: Build 
    runs-on: ubuntu-latest
    steps:
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
        
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: 192.186.0.115
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASS }}
