name: build and deploy 

on:
  push:
    branches: ["main"]
  
jobs:
  build: 
    name: Build 
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to harbor Container Registry
        uses: docker/login-action@v2
        with:
          registry: 108.143.193.224
          username: ${{ github.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASS }}
