name: build and deploy 

on:
  push:
    branches: ["main"]
  
jobs:
  build: 
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to Registry
        run: |
          sudo echo "${{ secrets.HUBCERTIFICATE }}" | sudo tee -a /etc/docker/certs.d/ofek.hugi:8443/ca.crt
          sudo echo "23.97.135.89 ofek.hugi" | sudo tee -a /etc/hosts
          sudo echo "{" | sudo tee -a /etc/docker/daemon.json
          sudo echo "    "insecure-registries" : [ "ofek.hugi:8443" ]" | sudo tee -a /etc/docker/daemon.json
          sudo echo "}" | sudo tee -a /etc/docker/daemon.json
          docker login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PASS }} ofek.hugi:8443
